sudo: required
language: python
services:
- docker

script:
- docker build -t joaomlneto-blender-build env
- wget https://download.blender.org/demo/eevee/race_spaceship/race_spaceship.blend
- ./run-script.sh race_spaceship.blend analyze.py
