sudo: required
language: python
services:
- docker

script:
- docker build -t joaomlneto-blender-build env
- wget https://download.blender.org/demo/eevee/race_spaceship/race_spaceship.blend
- docker run --rm -v $(pwd)/race_spaceship.blend:/file.blend -v $(pwd)/analyze.py:/script.py joaomlneto-blender-build /file.blend -P /script.py
